refresh_rate: 30 seconds

appenders:
    file:
        kind: file
        path: "logs/info.log"
        encoder:
            pattern: "{d} - {m}{n}"

    requests:
        kind: file
        path: "logs/requests.log"
        encoder:
            pattern: "{d} - {m}{n}"

root:
    level: warn
    appenders:
        - file

loggers:
    app::backend::db:
        level: info

    app::requests:
        level: info
        appenders:
            - requests
        additive: false
